spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:reviewing-test;MODE=MYSQL
    username: sa
    password:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  profiles:
    include: security